# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2280b6f1c646e056ed9df11e224e821d0000d8c7c9bdf9c87d43934613550383447e196300dcd37ff074c169390f8a53b22814e1e349d01b89e3392d3f97368c

test:
  secret_key_base: 4d638218557b5dd9424a0692fed0283d19048910de35cf75ad6dd34e957e9f168928498cd4c34773f24bce6919009735d375cfbb43db674ce2081404962d7777

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
